ICoder/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "Acoder Admin"
admin.site.site_title = "Acoder Admin"
admin.site.index_title = "Acoder Title"

urlpatterns = [
    path("recipe/",include('recipe.urls')),
    path("",include('home.urls')),
    path("users/",include('users.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
] 
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG : 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from .views import PostListView,PostSearchListView

app_name = "home" 

urlpatterns = [
    # path('', views.home,name='home'),
    path('', PostListView.as_view(), name="home"),
    path('home', views.home,name='Home'),
    path('contact', views.contact,name='contact'),
    path('about', views.about,name='about'),
    path('search', views.search,name='search'),
    # path('search', PostSearchListView.as_view(),name='search'),
]

recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import PostListView,PostDetailView,PostCreateView,UserPostListView,PostUpdateView,PostDeleteView


app_name = "recipe" 

urlpatterns = [
    path('my-recipe', PostListView.as_view(), name="recipeHome"),
    path('user/<str:username>',UserPostListView.as_view(),name='user-post'),
    path('recipe/<int:pk>/update/',PostUpdateView.as_view(),name='post-update'),
    path('recipe/<int:pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('new_recipe', views.newRecipe, name="new_recipe"),
    path('postComment', views.postComment, name="postComment"),
    path('recipe/<str:slug>', views.blogPost, name="recipePost")
    # path('<str:slug>', PostDetailView.as_view(), name="blogPost"),
    # path('', views.blogHome, name="blogHome"),
    # path('new_post', PostCreateView.as_view(), name="new_blog"),
]

home/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
     sno= models.AutoField(primary_key=True)
     name= models.CharField(max_length=255)
     phone= models.CharField(max_length=13)
     email= models.CharField(max_length=100)
     content= models.TextField()
     timeStamp=models.DateTimeField(auto_now_add=True, blank=True)

     def __str__(self):
          return "Message from " + self.name + ' - ' + self.email

templates/blog/blogHome.html
{% extends 'base.html' %}

{% block title %} BlogHome {% endblock title %}
 
    {% block js %}
      <script>
      let previews=document.getElementsByClassName('preview');
      Array.from(previews).forEach((element)=>{
          element.innerHTML=element.innerText;
      });
      </script>
      {% endblock js %}
      
{% block blogactive %} active {% endblock blogactive %} 


{% block body %}

<style>
    body{
        /* padding-left: 100px;
        background-color: black; */
        background-image: url("https://images.pexels.com/photos/1030947/pexels-photo-1030947.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1");
            background-size: cover;
            width: 100vw;
            /* height: 100vw; */
            /* padding-bottom: 40px; */
    }

    .container{
        background-color: white;
    }
</style>

<div class="container my-3">
    <h2>Recipes by {{user.username}} ({{ page_obj.paginator.count }})</h2>
    <div class="alert alert-warning bg-light p-3 m-2 d-md-flex justify-content-md-end">
        <a href="{% url 'home:home' %}"  class="btn btn-outline-success mr-4 rounded-pill"  role="button">View All Posts</a>
        <a href="{% url 'recipe:new_recipe' %}" class="btn btn-outline-success mr-4 rounded-pill"  role="button">Upload More New Post</a>
    </div>
    {% if allPosts %}
        {% for post in allPosts  %}
            <div class="row no-gutters align-items-center border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
                <div class="col-3 d-none d-lg-block p-3 align-items-center justify-content-center">
                    <img src="{{post.pic.url}}" class="img-thumbnail rounded-circle" style="height:180px;width:180px;" alt="img - {{post.author.username}}"> 
              

                    <!-- <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRySQWC0abJmDb6-ThxGNw0-7NtizbPveXdG6624agMbu98hLeDMJ84yyQQsf4AoZgThRg&usqp=CAU" style="height:180px;width:180px;" alt="" class="recipe_image"> -->
                </div>
            
                <div class="col p-4 d-flex flex-column position-static">
                    <strong class="d-inline-block mb-2 text-primary">Recipe  by {{post.author}} ({{post.views}})</strong>
                    <h3 class="mb-0"><a class="text-dark"href="{% url 'recipe:recipePost' post.title %}">{{post.title}} </a> </h3>
                    <div class="mb-1 text-muted">{{post.datetime}}</div>
                    <p class="card-text mb-auto mt-3">{{post.content|safe |truncatechars:200}}</p>
                    <div class="my-2">
                        <a href="{% url 'recipe:recipePost' post.title %}" role="button" class="btn btn-primary">Continue reading</a>
                    </div>
                    
                </div>
                {% comment %} <div class="col-auto d-none d-lg-block">
                    <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail">
                        <title>Placeholder</title>
                        <rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                    </svg>
                </div> {% endcomment %}
            </div>
        {% endfor %}
        <div class="mt-4">
            {% if is_paginated %}
                {% if page_obj.has_previous %}
                    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
                {% endif %}
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
                    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages}}">Last</a>
                {% endif %}
            {% endif %}
        </div>
    {% else %}
        <div class="alert alert-dismissible alert-danger">
            No Posts has been added yet....
        </div>
    {% endif %}
    </div>
 {% endblock %}

templates/blog/blogpost.html
{% extends 'base.html' %}
{% block title %} Blogpost{% endblock title %}
{% block body %}

<style>
    .container_main{
        /* background-color: blue; */
        display: flex;
        flex-direction: column;
    }
    .comments_main{
        margin-top: 50px;
        /* background-color: blue; */
    }
    .recipe_image{
        width: 500px;
    }
</style>

{% load humanize %}
{% load extras %}
<div class="container_main">
    <div class="container my-3">
        <h2 class="blog-post-title">{{post.title.capitalize}}</h2>
        <p class="blog-post-meta ml-2">
            {{post.timeStamp}} by <a href="{% url 'recipe:user-post' post.author.username %}">{{post.author}}</a> ( <span >{{post.views}} views</span> )
        </p>
        
        <div>
            {% if post.author == user %}
                <a class="btn btn-secondary btn-sm mt-1 mb-2" href="{% url 'recipe:post-update' post.sno %}">Update Post</a>
                <a class="btn btn-danger btn-sm mt-1 mb-2" href="{% url 'recipe:post-delete' post.sno %}">Delete</a>
            {% endif %}
        </div>

        <img src="{{post.pic.url}}"  alt="" class="recipe_image">
       

        {% comment %} <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRySQWC0abJmDb6-ThxGNw0-7NtizbPveXdG6624agMbu98hLeDMJ84yyQQsf4AoZgThRg&usqp=CAU" alt="" class="recipe_image"> {% endcomment %}
       
        <!-- <img src="{{post.author.profile.image.url}}" class="img-thumbnail rounded-circle" style="height:180px;width:180px;" alt="img - {{post.author.username}}"> -->
        <!-- <p>safe</p> -->
        <hr class="my-5">
        <h2 class="blog-post-title">Ingredients used in recipe</h2>
        <p>{{post.ingredients|safe}}</p>
        <hr class="my-5">
        <br>
        <!-- <hr class="my-5"> -->
        <h1>Recipe Steps</h1>
        <hr class="my-4">

        <p>{{post.content|safe}}</p>
        <br>
        {% comment %} <hr class="my-3" > {% endcomment %}
    </div>
    
    <div class="container comments_main">
        <h2> Comments ({{comments.count}}) </h2>
        <div class="my-2">
            {% if user.is_authenticated %}
            <form action="/recipe/postComment" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">Post Comment </label>
                    <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                </div>
                <input type="hidden" name="postSno" value="{{post.sno}}">
                <input type="hidden" name="parentSno" value="">
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% else %}
            Please login to post a comment
            {% endif %}
        </div>
        {% for comment in comments %}
        <div class="row my-3">
            <div class="col-md-1  ">
                <img class="rounded mx-auto d-block w-100 border border-dark p-2" src="/static/img/user.png" alt="user">
            </div>
            <div class="col-md-11 ">
                <b> {{comment.user.username}} </b> <span class="badge badge-secondary ">{{comment.timestamp| naturaltime}}</span>
                <div>{{comment.comment}}</div>
                <div class="reply mx-0">
                    {% if user.is_authenticated %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.sno}}" aria-expanded="false" aria-controls="replyBox{{comment.sno}}">
                        Reply
                    </button>
                    <div class="collapse" id="replyBox{{comment.sno}}">
                        <div class="card card-body my-2">
                            <form action="/recipe/postComment" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="comment">Post a reply </label>
                                    <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                                    <input type="hidden" name="parentSno" value="{{comment.sno}}">
                                </div>
                                <input type="hidden" name="postSno" value="{{post.sno}}">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                    {% else %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.sno}}" aria-expanded="false" aria-controls="replyBox{{comment.sno}}">
                        Login to reply
                    </button>
                    {% endif %}
                    <div class="replies my-2 ">
                        {% for reply in replyDict|get_val:comment.sno %}
                        <div class="row my-2">
                            <div class="col-md-1 ">
                                <img class="rounded mx-auto d-block w-75 my-2 border border-dark p-2" src="/static/img/user.png" alt="user">
                            </div>
                            <div class="col-md-11">
                                <div class="col-md-11 ">
                                    <b> {{reply.user.username}} </b> <span class="badge badge-secondary ">{{reply.timestamp| naturaltime}}</span>
                                    <div>{{reply.comment}}</div>
                                </div>
                                <br>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% block title %} Blogpost{% endblock title %}
{% block body %}


{% load humanize %}
{% load extras %}
<div class="container my-3">
    <h2 class="blog-post-title">{{post.title}}</h2>
    <p class="blog-post-meta">{{post.timeStamp}} by <a href="{% url 'recipe:user-post' post.author.username %}">{{post.author.username}}</a> (<span > {{post.views}} views</span>)</p>
    <p class="mt-2">{{post.content|safe}}</p>
    <br>
    <br>
    <hr class="mt-4" >
</div>

<div class="row">
    <div class="container">
        <h2> Comments ({{comments.count}}) </h2>
        <div class="my-2">
            {% if user.is_authenticated %}
            <form action="/recipe/postComment" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="exampleInputEmail1">Post Comment </label>
                    <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                </div>
                <input type="hidden" name="postSno" value="{{post.sno}}">
                <input type="hidden" name="parentSno" value="">
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% else %}
            Please login to post a comment
            {% endif %}
        </div>
        {% for comment in comments %}
        <div class="row my-3">
            <div class="col-md-1  ">
                <img class="rounded mx-auto d-block w-100 border border-dark p-2" src="/static/img/user.png" alt="user">
            </div>
            <div class="col-md-11 ">
                <b> {{comment.user.username}} </b> <span class="badge badge-secondary ">{{comment.timestamp| naturaltime}}</span>
                <div>{{comment.comment}}</div>
                <div class="reply mx-0">
                    {% if user.is_authenticated %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.sno}}" aria-expanded="false" aria-controls="replyBox{{comment.sno}}">
                        Reply
                    </button>
                    <div class="collapse" id="replyBox{{comment.sno}}">
                        <div class="card card-body my-2">
                            <form action="/recipe/postComment" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="comment">Post a reply </label>
                                    <input type="text" class="form-control" name="comment" placeholder="Enter comment here">
                                    <input type="hidden" name="parentSno" value="{{comment.sno}}">
                                </div>
                                <input type="hidden" name="postSno" value="{{post.sno}}">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </form>
                        </div>
                    </div>
                    {% else %}
                    <button class="btn btn-sm btn-primary" type="button" data-toggle="collapse" data-target="#replyBox{{comment.sno}}" aria-expanded="false" aria-controls="replyBox{{comment.sno}}">
                        Login to reply
                    </button>
                    {% endif %}
                    <div class="replies my-2 ">
                        {% for reply in replyDict|get_val:comment.sno %}
                        <div class="row my-2">
                            <div class="col-md-1 ">
                                <img class="rounded mx-auto d-block w-75 my-2 border border-dark p-2" src="/static/img/user.png" alt="user">
                            </div>
                            <div class="col-md-11">
                                <div class="col-md-11 ">
                                    <b> {{reply.user.username}} </b> <span class="badge badge-secondary ">{{reply.timestamp| naturaltime}}</span>
                                    <div>{{reply.comment}}</div>
                                </div>
                                <br>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}
 
{% block title %} New_Recipe - new Recipe{% endblock title %}
 
{% comment %}       
{% block blogactive %} active {% endblock blogactive %} 
{% endcomment %}
{% block titlejs %}
    <script src="https://cdn.tiny.cloud/1/thgg07r92awby69y1zr09hhggwr673aa28du6l6oo7pavwxa/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script>
    tinymce.init({
        selector: '#id_content',
        cleanup_on_startup: 'True',
        custom_undo_redo_levels: 20,
        
        theme: 'silver',
        plugins: ' textcolor save link image media preview codesample contextmenu code lists fullscreen  insertdatetime  nonbreaking contextmenu directionality searchreplace wordcount visualblocks visualchars code fullscreen autolink lists  charmap print  hr anchor pagebreak',
        toolbar1: ' fullscreen preview bold italic underline | fontselect, fontsizeselect  | forecolor backcolor | alignleft alignright | aligncenter alignjustify | indent outdent | bullist numlist table | link image media | codesample ',
        toolbar2: ' visualblocks visualchars | charmap hr pagebreak nonbreaking anchor |  code ',
        contextmenu: 'formats | link image',
        menubar: 'True',
        statusbar: 'True',
    });
    </script>
    <style>
        #id_content{
            min-height:500px;
        }
    </style>
{% endblock titlejs %}

{% load crispy_forms_tags %}
{% block body %}
<div class="container col-8 my-3 align-self-center border">
    <h2 style="margin-left:-2%;" class="m-2 text-center text-muted">New Post</h2>
    <hr>
    {% comment %} <div class="row col-10"> {% endcomment %}
    <div>
        <form action="" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                {{ form|crispy }}         
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type= "submit">Post</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/blog/recipe_confirm_delete.html
{% extends 'base.html' %}

{% block title %} Delete Blog {% endblock title %}
 
{% comment %}       
{% block blogactive %} active {% endblock blogactive %} 
{% endcomment %}

{% block body %}
<div class="container col-6 my-3 align-self-center border border-warning">
    <h2 style="margin-left:-2%;" class="m-2 text-center text-muted">Delete Post</h2>
    <hr>
    <p>
       <h4>Are you sure you want to delete the post <br><span style="color:red;font-size:1.2em;"> "{{object.title}}" </span></h4> 
    </p>
    {% comment %} <div class="row col-10"> {% endcomment %}
    <div>
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type= "submit">yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'recipe:recipePost' object.title %}">Cancel</a>
            </div>

        </form>
    </div>
</div>
{% endblock %}

templates/blog/userBlog.html
{% extends 'base.html' %}

{% block title %} Recipe - {{view.kwargs.username}} {% endblock title %}
 
    {% block js %}
      <script>
      let previews=document.getElementsByClassName('preview');
      Array.from(previews).forEach((element)=>{
          element.innerHTML=element.innerText;
      });
      </script>
      {% endblock js %}

     
      
{% comment %} {% block blogactive %} active {% endblock blogactive %}  {% endcomment %}

<style>
    .container_main{
        width: 500px;
        /* background-color: blueviolet; */
    }
</style>
{% block body %}


<div class="container my-3 container_main">
    <h2>Recipes by {{view.kwargs.username}} ({{ page_obj.paginator.count }})</h2>
    {% for post in allPosts  %}
        <div class="row no-gutters border rounded align-items-center overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
            <div class="col-3 d-none d-lg-block p-3 align-self-center justify-content-center">
                <img src="{{post.pic.url}}" class="img-thumbnail rounded-circle" style="height:180px;width:180px;" alt="img - {{post.author.username}}">
            </div>
            <div class="col p-4 d-flex flex-column position-static">
                <strong class="d-inline-block mb-2 text-primary">Recipe  by {{post.author}} ({{post.views}})</strong>
                <h3 class="mb-0"><a class="text-dark"href="{% url 'recipe:recipePost' post.title %}">{{post.title}} </a> </h3>
                <div class="mb-1 text-muted">{{post.datetime}}</div>
                <p class="card-text mb-auto mt-3">{{post.content|safe |truncatechars:200}}</p>
                <div class="my-2">
                    <a href="{% url 'recipe:recipePost' post.title %}" role="button" class="btn btn-primary">Continue reading</a>
                </div>
                
            </div>
        </div>
    {% endfor %}
    <div class="mt-4">
        {% if is_paginated %}
            {% if page_obj.has_previous %}
                <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
                <a class="btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
            {% endif %}
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
                <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages}}">Last</a>
            {% endif %}
        {% endif %}
    </div>
</div>
 {% endblock %}