ICoder/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "Acoder Admin"
admin.site.site_title = "Acoder Admin"
admin.site.index_title = "Acoder Title"

urlpatterns = [
    path("recipe/",include('recipe.urls')),
    path("",include('home.urls')),
    path("users/",include('users.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
] 
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG : 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from .views import PostListView,PostSearchListView

app_name = "home" 

urlpatterns = [
    # path('', views.home,name='home'),
    path('', PostListView.as_view(), name="home"),
    path('home', views.home,name='Home'),
    path('contact', views.contact,name='contact'),
    path('about', views.about,name='about'),
    path('search', views.search,name='search'),
    # path('search', PostSearchListView.as_view(),name='search'),
]

recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import PostListView,PostDetailView,PostCreateView,UserPostListView,PostUpdateView,PostDeleteView


app_name = "recipe" 

urlpatterns = [
    path('my-recipe', PostListView.as_view(), name="recipeHome"),
    path('user/<str:username>',UserPostListView.as_view(),name='user-post'),
    path('recipe/<int:pk>/update/',PostUpdateView.as_view(),name='post-update'),
    path('recipe/<int:pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('new_recipe', views.newRecipe, name="new_recipe"),
    path('postComment', views.postComment, name="postComment"),
    path('recipe/<str:slug>', views.blogPost, name="recipePost")
    # path('<str:slug>', PostDetailView.as_view(), name="blogPost"),
    # path('', views.blogHome, name="blogHome"),
    # path('new_post', PostCreateView.as_view(), name="new_blog"),
]

users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


app_name = "users" 

urlpatterns = [
    path("register",views.register,name="register"),
    path("login",views.userlogin,name="login"),
    path("logout",views.HandleLogout,name="logout"),
    path("profile",views.profile,name="profile"),
    path("update_profile",views.updateProfile,name="updateprofile"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path("password-reset",
        auth_views.PasswordResetView.as_view(
                template_name="users/password_reset.html",
                email_template_name = 'users/password_reset_email.html'
            ),
        name="password_reset"),
    path("password-reset/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
            ),
        name="password_reset_done"),
    # path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    # path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),

    # path("logout",auth_views.LogoutView.as_view(template_name="users/logout.html"),name="logout"),
]
#  owxynejqccfqlpdw

templates/base.html
<!doctype html>
<html lang="en">




<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <title>{% block title %} {% endblock title %}</title>
    {% block titlejs %}{% endblock titlejs %}
    <style>
        .blog-footer {
            padding: 2.5rem 0;
            color: #727272;
            text-align: center;
            background-color: #f9f9f9;
            border-top: .05rem solid #e5e5e5;
            margin-top: 20px;
          
        }
        body{
            overflow-x: hidden;
        }
        .navbar {
            width: 100vw;
  background-color: rgb(74, 77, 243);
}
.nav-link{
    color: white;
    /* background-color: yellow; */
    /* border-bottom: 3px solid white; */
    /* border-bottom-left-radius: 10px; */
    border-bottom: 3px solid rgb(74, 77, 243);
    
    
}

.nav-link:hover{
    /* color: rgb(194, 34, 34); */
    /* background-color: yellow; */
    border-bottom: 3px solid white;
    /* border-bottom-left-radius: 10px; */
    
    color: white;
    
}

.btn-search{
    background-color: white;
    color: black;
    border-radius: 10px;
}

.btn-search:hover{
    background-color: rgb(5, 179, 5);
}

.admin-btn{
    background-color: rgb(5, 179, 5);
    color: white;
    border-radius: 10px;
}

.recipe-input{
    border-radius: 10px;
    outline: none;
    border: none;
}

.navbar-brand{
    color: white;
}

.navbar-brand:hover{
    color: white; 
}

.blog-footer{
    width: 100vw;
}
    </style>
</head>

<body>

    <nav class="navbar navbar-expand-lg " id='top'>
        <a class="navbar-brand" href="/">RecipeApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% block homeactive %}  {% endblock homeactive %}">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% block aboutactive %}  {% endblock aboutactive %}">
                    <a class="nav-link" href="/about">About</a>
                </li>
                <li class="nav-item {% block contactactive %}  {% endblock contactactive %} ">
                    <a class="nav-link" href="/contact">Contact</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item {% block blogactive %}  {% endblock blogactive %} ">
                    <a class="nav-link" href="{% url 'recipe:recipeHome' %}">My Recipes</a>
                </li>
                {% endif %}
            </ul>
            <div class="ml-auto form-inline ">
                <form method="get" action="/search" class="my-2 my-lg-0 mx-3">
                    <input class="form-control mr-sm-2 recipe-input" type="search" placeholder="Search Recipes here" aria-label="Search" name="query" id="query">
                    <button class="btn btn-primary my-2 my-sm-0 btn-search" type="submit">Search</button>
                    <a href="/admin" role="button" target="_blank" class="btn btn-outline-success m-2 my-sm-0 admin-btn"> Admin Panel </a>
                </form>



                {% if user.is_authenticated %}
                <ul class="navbar-nav mr-2">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {% block useractive %}  {% endblock useractive %}" href='#' id="navbarDropdown" role="button" data-toggle="dropdown"> Welcome {{request.user}}</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'recipe:new_recipe'%}">New Post</a>
                            <a class="dropdown-item" href="{% url 'users:profile'%}">Profile</a>
                            <a class="dropdown-item" href="{% url 'users:logout'%}">Logout</a>
                        </div>
                    </li>
                </ul>
            </div>
            {% else %}
            <!-- Button to  trigger Login modal -->
            <!-- <button type="button" class="btn btn-primary mr-2" data-toggle="modal" data-target="#loginModal">
            Login </button> -->
            <a href="{% url 'users:login' %}" class="btn btn-primary mr-2">
                Login
            </a>
            <a class="btn btn-primary mr-2" href="{% url 'users:register' %}"> Sign Up</a>
            <!-- <button type="button"  data-toggle="modal" data-target="#">
            </button>  -->
            {% endif %}


        </div>
    </nav>
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>Message : </strong> {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}

    <!-- SignUp Modal -->
    <div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="signupModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="signupModalTitle">SignUp Here</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
                </div>
                <div class="modal-body">
                    <form action="/signup" method='post'>
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="username" name="username" placeholder="Choose a unique username" required>
                        </div>
                        <div class="form-group">
                            <label for="fname">First Name</label>
                            <input type="text" class="form-control" id="fname" name="fname" placeholder="Enter Your First Name" required>
                        </div>
                        <div class="form-group">
                            <label for="lname">Last Name</label>
                            <input type="text" class="form-control" id="lname" name="lname" placeholder="Enter Your Last Name" required>
                        </div>
                        <div class="form-group">
                            <label for="email">Email address</label>
                            <input type="email" class="form-control" id="email" name="email" placeholder="name@example.com" required>
                        </div>
                        <div class="form-group">
                            <label for="pass1">Choose a password</label>
                            <input type="password" class="form-control" id="pass1" name="pass1" placeholder="Choose Your Password" required>
                        </div>
                        <div class="form-group">
                            <label for="pass2">Confirm Password</label>
                            <input type="password" class="form-control" id="pass2" name="pass2" placeholder="Enter your password again" required>
                        </div>


                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>

    <main style="min-height:600px;">

        {% block body %} {% endblock body %} {% block js %} {% endblock js %}

    </main>

    <!-- Login Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalTitle">Login Here</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
                </div>
                <div class="modal-body">
                    <form action="/users/login" method="POST"> {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username</label>
                            <input type="text" class="form-control" id="loginusername" name="loginusername" placeholder="Enter your username " required>
                        </div>
                        <div class="form-group">
                            <label for="pass">Enter your password </label>
                            <input type="password" class="form-control" id="loginpassword" name="loginpassword" placeholder="Enter your password " required>
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <div class="modal-footer">
                </div>
            </div>
        </div>
    </div>


    <footer class="blog-footer">
        <p>Web template built for <a href="">Recipe application</a> by <a href="https://www.linkedin.com/in/ajinkya-sahu/">Ajinkya Sahu</a>.</p>
        <p>
            <a href="#top">Back to top</a>
        </p>
    </footer>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>