ICoder/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


admin.site.site_header = "Acoder Admin"
admin.site.site_title = "Acoder Admin"
admin.site.index_title = "Acoder Title"

urlpatterns = [
    path("recipe/",include('recipe.urls')),
    path("",include('home.urls')),
    path("users/",include('users.urls')),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
] 
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG : 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views
from .views import PostListView,PostSearchListView

app_name = "home" 

urlpatterns = [
    # path('', views.home,name='home'),
    path('', PostListView.as_view(), name="home"),
    path('home', views.home,name='Home'),
    path('contact', views.contact,name='contact'),
    path('about', views.about,name='about'),
    path('search', views.search,name='search'),
    # path('search', PostSearchListView.as_view(),name='search'),
]

recipe/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from .views import PostListView,PostDetailView,PostCreateView,UserPostListView,PostUpdateView,PostDeleteView


app_name = "recipe" 

urlpatterns = [
    path('my-recipe', PostListView.as_view(), name="recipeHome"),
    path('user/<str:username>',UserPostListView.as_view(),name='user-post'),
    path('recipe/<int:pk>/update/',PostUpdateView.as_view(),name='post-update'),
    path('recipe/<int:pk>/delete/',PostDeleteView.as_view(),name='post-delete'),
    path('new_recipe', views.newRecipe, name="new_recipe"),
    path('postComment', views.postComment, name="postComment"),
    path('recipe/<str:slug>', views.blogPost, name="recipePost")
    # path('<str:slug>', PostDetailView.as_view(), name="blogPost"),
    # path('', views.blogHome, name="blogHome"),
    # path('new_post', PostCreateView.as_view(), name="new_blog"),
]

users/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views


app_name = "users" 

urlpatterns = [
    path("register",views.register,name="register"),
    path("login",views.userlogin,name="login"),
    path("logout",views.HandleLogout,name="logout"),
    path("profile",views.profile,name="profile"),
    path("update_profile",views.updateProfile,name="updateprofile"),
    path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path("password-reset",
        auth_views.PasswordResetView.as_view(
                template_name="users/password_reset.html",
                email_template_name = 'users/password_reset_email.html'
            ),
        name="password_reset"),
    path("password-reset/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
            ),
        name="password_reset_done"),
    # path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    # path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),

    # path("logout",auth_views.LogoutView.as_view(template_name="users/logout.html"),name="logout"),
]
#  owxynejqccfqlpdw

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default="default.jpg",upload_to = 'profile_pics')

    def __str__(self):
        return f"{self.user.username} Profile"
        
    

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class LoginForm(forms.Form):
    user_id = forms.CharField(label='User Id', required = True)
    password = forms.CharField(label='Password' , max_length=32, widget=forms.PasswordInput)


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required = True)
    f_name = forms.CharField(label='First name', max_length=100)
    l_name = forms.CharField(label='Last name', max_length=100)

    class Meta:
        model = User
        fields = ['f_name','l_name',"username",'email','password1','password2']



class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(required = True)
    # f_name = forms.CharField(label='First name', max_length=100)
    # l_name = forms.CharField(label='Last name', max_length=100)

    class Meta:
        model = User
        fields = ['first_name','last_name','email']

    
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image"]

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
# Create your views here.
from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegisterForm, LoginForm, UserUpdateForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required()
def updateProfile(request):

    if request.method == "POST":    
        u_form = UserUpdateForm(request.POST,instance = request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance = request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,f"Your Profile has been updated successfully!")
            return redirect("users:profile")
    else:
        u_form = UserUpdateForm(instance = request.user)
        p_form = ProfileUpdateForm(instance = request.user.profile)
    context = {
        "u_form":u_form,
        "p_form":p_form
    }
    return render(request,"users/updateprofile.html",context)


@login_required()
def profile(request):
    return render(request,"users/profile.html")   


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            # form.save()
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            f_name = form.cleaned_data.get('f_name')
            l_name = form.cleaned_data.get('l_name')
            password = form.cleaned_data.get('password1')
            user = User.objects.create_user(username = username,password = password,email = email,first_name = f_name,last_name = l_name)
            user.save()
            messages.success(request,f"Account has been created for { username }!")
            return redirect("/")
    else:
        form = UserRegisterForm()
    return render(request,'users/register.html',{"form":form})
    # return render(request,'home/home1.html',{"form":form})


def userlogin(request):
    if request.method == "POST":
        # loginusername=request.POST['loginusername']
        # loginpassword =request.POST['loginpassword']
        form = LoginForm(request.POST) 
        if form.is_valid():
            loginusername=form.cleaned_data.get('user_id')
            loginpassword=form.cleaned_data.get('password')
            # print(loginusername,loginpassword)
            user = authenticate(username=loginusername , password= loginpassword)
            if user is not None :
                login(request,user)
                messages.success(request,"Successfully Logged In")
                return redirect("home:home")
                # return render(request,"home/home.html")
            else:
                messages.error(request,"Unsuccessfull Logged In. Invalid credentials")
                return redirect("users:login")
        else: 
            return render(request,"users/login.html",{"form":form})
    return render(request,"users/login.html",{"form":LoginForm()})


@login_required()
def HandleLogout(request):
    logout(request)
    messages.success(request,"Successfully Loged out....")
    return redirect("home:home")

templates/users/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock title %}
 
{% comment %}       
{% block blogactive %} active {% endblock blogactive %} 
{% endcomment %}

{% load crispy_forms_tags %}
{% block body %}
<div class="container col-6 my-3 align-self-center border">
    <h2 style="margin-left:-2%;" class="m-2 text-dark">Enter your credentials...</h2>
    <hr>
    <div>
        <form action="/users/login" method="post">

            {% csrf_token %}
    
            <fieldset class="form-group">
                {{ form|crispy }}         
            </fieldset>

            <div class="form-group">
                <button class="btn btn-outline-info" type= "submit">Sign In</button>
            </div>

            <div class="border-top pt-3">
                <small class="text-muted">
                   Do Not Have An Account? <a class="ml-2" href="#">Sign Up</a>
                </small>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/users/logout.html
{% extends 'base.html' %} {% block title %} Home{% endblock title %} {% block homeactive %}active{% endblock homeactive %} {% block body %}
<div class="container">
    <div class="alert alert-success alert-dismissible fade show my-2" role="alert">
        <h3>You have been Logged Out Successfull.</h3>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>
<div class="container">
    <div class="jumbotron my-3">
        <h1 class="display-4">Welcome to iCoder!</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <a class="btn btn-primary btn-lg" href="/recipe" role="button">Go to Blog</a>
    </div>
</div>

<div class="container">
    <h2>Popular Recipeposts</h2>
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 my-4 position-relative">
        <div class="col p-4 d-flex flex-column position-static">
            <strong class="d-inline-block mb-2 text-primary">World</strong>
            <h3 class="mb-0">Featured post</h3>
            <div class="mb-1 text-muted">Nov 12</div>
            <p class="card-text mb-auto">This is a wider card with supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="stretched-link">Continue reading</a>
        </div>
        <div class="col-auto d-none d-lg-block">
            <svg class="bd-placeholder-img" width="200" height="250" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: Thumbnail"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"></rect><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
        </div>
    </div>
</div>

{% endblock %}
{% block js %}
    windows.location.href = "/";
{% endblock %}

templates/users/password_reset.html
{% extends 'base.html' %}

{% block title %} Reset password {% endblock title %}
 
{% comment %}       
{% block blogactive %} active {% endblock blogactive %} 
{% endcomment %}

{% load crispy_forms_tags %}
{% block body %}
<div class="container col-6 my-3 align-self-center border">
    <h2 style="margin-left:-2%;" class="m-2 text-dark">Reset Password</h2>
    <hr>
    <div>
        <form method="post">

            {% csrf_token %}
    
            <fieldset class="form-group">
                {{ form|crispy }}         
            </fieldset>

            <div class="form-group">
                <button class="btn btn-outline-info" type= "submit">Request Password Reset</button>
            </div>

            {% comment %} <div class="border-top pt-3">
                <small class="text-muted">
                   Do Not Have An Account? <a class="ml-2" href="#">Sign Up</a>
                </small>
            </div> {% endcomment %}
        </form>
    </div>
</div>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %} Reset password {% endblock title %}
 
{% comment %}       
{% block blogactive %} active {% endblock blogactive %} 
{% endcomment %}

{% load crispy_forms_tags %}
{% block body %}
<div class="container col-6 my-3 align-self-center border">
    <h2 style="margin-left:-2%;" class="m-2 text-dark">Reset Password</h2>
    <hr>
    <div>
        <form method="post">

            {% csrf_token %}
    
            <fieldset class="form-group">
                {{ form|crispy }}         
            </fieldset>

            <div class="form-group">
                <button class="btn btn-outline-info" type= "submit">Reset password</button>
            </div>

            {% comment %} <div class="border-top pt-3">
                <small class="text-muted">
                   Do Not Have An Account? <a class="ml-2" href="#">Sign Up</a>
                </small>
            </div> {% endcomment %}
        </form>
    </div>
</div>
{% endblock %}

templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block title %} Email sent {% endblock title %}
 
{% comment %}       
{% block blogactive %} active {% endblock blogactive %} 
{% endcomment %}

{% comment %} {% load crispy_forms_tags %} {% endcomment %}
{% block body %}
<div class="container col-6 my-3 align-self-center border">
   <div class="alert alert-info">
        <h3>An eamil is sent with the instructions to reset the password.</h3>
   </div>
</div>
{% endblock %}

templates/users/password_reset_email.html
{% extends 'base.html' %}

{% block title %} Email sent {% endblock title %}
 
{% comment %}       
{% block blogactive %} active {% endblock blogactive %} 
{% endcomment %}

{% comment %} {% load crispy_forms_tags %} {% endcomment %}
{% block body %}
<div class="container col-6 my-3 align-self-center border">
   <div class="alert alert-info">
        <h3>An eamil is sent with the instructions to reset the password.
        Email template</h3>
   </div>
</div>
{% endblock %}

templates/users/profile.html
{% extends 'base.html' %} {% block title %} Profile{% endblock title %} {% block useractive %}active{% endblock useractive %} {% block body %}

<div class="container my-4">

    <div class="card border-warning">
        <div class="card-header text-white bg-success border-warning">
            <h3 class="card-title">Welcome <b>{{user.username}}</b> to your Profile</h3>
        </div>
        <div class="card-body">
            <!-- <h5 class="card-title">Special title treatment 1</h5> -->
            <div class="row align-items-center">
                <div class="col-sm-4">
                    <div class="card border-warning">
                        <div class="card-body">
                            <img src="{{user.profile.image.url}}" class="card-img img-fluid rounded" alt="{{user.username}} image">
                        </div>
                    </div>
                </div>
                <div class="col-sm-8">
                    <div class="card border-warning ">
                        <div class="card-body">
                            <!-- <h5 class="card-title">{{user.first_name}} {{user.last_name}}</h5> -->
                            <!-- <p class="card-text">{{user.email}}</p> -->
                            <form>
                                <div class=" mb-3">
                                    <label for="users_fullname" class="form-label text-start">Full Name</label>
                                    <input class="form-control" type="text" id="users_fullname" placeholder="{{user.first_name}} {{user.last_name}}" aria-label="{{user.first_name}} {{user.last_name}}" readonly disabled>
                                </div>
                                <div class=" mb-3">
                                    <label for="users_username" class="form-label text-start">User Name</label>
                                    <input class="form-control" type="text" id="users_username" placeholder="{{user.username}}" aria-label="{{user.username}}" readonly disabled>
                                </div>
                                <div class=" mb-3">
                                    <label for="users_email" class="form-label text-start">E-Mail</label>
                                    <input class="form-control" type="email" id="users_email" placeholder="{{user.email}}" aria-label="{{user.email}}" readonly disabled>
                                </div>
                            </form>
                            <!-- <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                <a class="btn btn-outline-primary btn-sm mr-2" type="button">My Posts</a>
                                <a class="btn btn-outline-primary btn-sm me-md-2" type="button">Update Profile</a>
                            </div> -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
        </div>
        <div class="card-footer text-muted border-warning">
            <!-- 2 days ago -->
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <a class="btn btn-outline-primary btn-sm mr-4 rounded-pill" type="button" href="{% url 'recipe:recipeHome' %}">My Posts</a>
                <a class="btn btn-outline-primary btn-sm me-md-4 rounded-pill" type="button" href="{% url 'users:updateprofile' %}">Update Profile</a>
            </div>
        </div>
    </div>

</div>


{% endblock %}

templates/users/register.html
{% extends 'base.html' %}

{% block title %} Registration {% endblock title %}
 
{% comment %}       
{% block blogactive %} active {% endblock blogactive %} 
{% endcomment %}

{% load crispy_forms_tags %}
{% block body %}
<div class="container col-6 my-3 align-self-center border">
    <h2 style="margin-left:-2%;" class="m-2 text-center text-muted">Register Yourself</h2>
    <hr>
    {% comment %} <div class="row col-10"> {% endcomment %}
    <div>
        <form action="/users/register" method="post">

            {% csrf_token %}
    
            <fieldset class="form-group">
                {{ form|crispy }}         
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type= "submit">Sign Up</button>
            </div>

            <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="#">Sign In</a>
                </small>
            </div>
        </form>
    </div>
</div>
{% endblock %}

templates/users/updateprofile.html
{% extends 'base.html' %} {% block title %} Profile{% endblock title %} {% block useractive %}active{% endblock useractive %} {% block body %}
{% load crispy_forms_tags %}
<div class="container my-4">

    <div class="card border-warning">
        <div class="card-header bg-success border-warning">
            <h2 style="margin-left:-2%;" class="m-2 text-center" style="color:black;"><span style="color:White;" class="text-light">@{{user.username}}</span> - Update your Profile</h2>
        </div>
        <div class="card-body">
        {% comment %} <hr> {% endcomment %}
            <div>
                <form action="" method="post" enctype = "multipart/form-data">

                    {% csrf_token %}
            
                    <fieldset class="form-group">
                        {{ u_form|crispy }}         
                        {{ p_form|crispy }}         
                        </fieldset>
                    <div class="form-group mt-3">
                        <button class="btn btn-outline-info" type= "submit">Update</button>
                    </div>
                </form>
                    
            {% comment %} </div> {% endcomment %}
            </div>
        </div>
        <div class="card-footer text-muted border-warning">
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                <small class="text-muted">
                    Everything is fine... <a class="ml-2" href="users:profile">go back to the profile page</a>
                </small>
            </div>
        </div>
    </div>
    

</div>


{% endblock %}